<a href="https://colab.research.google.com/github/oceanfishYU/Python_practise/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#0309

##陣列初始化

###由列表產生陣列

In [ ]:
mylist=[1,2,3]
mylist

[1, 2, 3]

In [ ]:
mylist*2

[1, 2, 3, 1, 2, 3]

In [ ]:
import numpy as an

import numpy這整個程式碼叫做an

In [ ]:
bc = an.array(mylist)
bc

array([1, 2, 3])

另bc為由mylist產生的陣列(一維陣列)

In [ ]:
bc*2

array([2, 4, 6])

陣列*n會等於陣列中的值乘以n，跟列表不同

###由函式產生陣列

In [ ]:
an.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

產生一個2列4行的陣列，並且面的值都是0

In [ ]:
an.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

產生一個2列4行的陣列，並且面的值都是1

In [ ]:
an.full((2,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

產生一個2列4行的陣列，並且面的值都是7

In [ ]:
an.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

產生一個2列4行的陣列，並且面的值都是1

In [ ]:
an.ones((3,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

產生一個2列4行的陣列，並且面的值都是1，這是一組，然後有3組(3組2列4行值為1的陣列)

In [ ]:
an.ones((2,3,2,4))

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

產生一個2列4行值為1並且有3組的陣列，這是一份，然後有2份(3組2列4行值為1的陣列並且有2份)

#陣列新增